FROM node:13.7.0 AS builder
WORKDIR /app/

COPY package.json yarn.lock ./
RUN yarn install

COPY ./ ./
RUN yarn build


FROM nginx
COPY --from=builder /app/build/ /usr/share/nginx/html/

COPY default.conf /etc/nginx/conf.d/

EXPOSE 80